server:
  port: ${random.int[10000,19999]}
spring:
  redis:
    host: 192.168.60.111
    port: 6379
    #password: # Redis 服务器密码，默认为空。生产中，一定要设置 Redis 密码！
    #database: 0 # Redis 数据库号，默认为 0 。
    #timeout: 0 # Redis 连接超时时间，单位：毫秒。
    # 对应 RedisProperties.Jedis 内部类
    lettuce:
      pool:
        max-active: 200 # 连接池最大连接数，默认为 8 。使用负数表示没有限制。
        min-idle: 10    # 默认连接数最小空闲的连接数，默认为 8 。使用负数表示没有限制
        max-idle: 20    # 默认连接池最小空闲的连接数，默认为 0 。允许设置 0 和 正数。
        max-wait: -1    # 连接池最大阻塞等待时间，单位：毫秒。默认为 -1 ，表示不限制。
